# Site
name: "The Master of None"
description: "It's a little bit of everything"
meta_description: "Blogging about everything."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: /
google_analytics: 'UA-120891610-1'
disqus: 'the-master-of-none'
mailchimp-list: ''

# Authors
authors:
  TJ:
    name: TJ Dugan
    display_name: TJ
    gravatar: 
    email: tdugan01@nycap.rr.com
    web: https://www.tjdugan.com
    twitter: https://twitter.com/ir1_2000
    description: ""

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown
highlighter: rouge