# Site
name: "The Master of None"
description: "It's a little bit of everything"
meta_description: "Blogging about everything."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: /
google_analytics: 'UA-120891610-1'
disqus: 'the-master-of-none'
mailchimp-list: 'https://the-master-of-none.us18.list-manage.com/subscribe/post?u=3d733f8878294857d743ded7f&amp;id=e0b578856f'

# Authors
authors:
  TJ:
    name: TJ Dugan
    display_name: TJ Dugan
    gravatar: 52a24838ee6484f4b14049724811b517
    email: tdugan01@nycap.rr.com
    web: https://www.tjdugan.com
    twitter: https://twitter.com/ir1_2000
    description: ""

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown
highlighter: rouge